config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  get "dashboard", to: "dashboard#index"

  resources :boards do
    resources :lists
  end

  resources :lists do
    resources :items
  end

  namespace :api do
    resources :boards do
      resources :lists, only: [:index], controller: "lists"
      resources :list_positions, only: [:index, :update], controller: "list_positions"
    end
    put "item_positions", to: "item_positions#update"

    resources :items, only: :show
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  has_many :lists, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  before_save :update_completed_at, if: :list_done?

  validates :title, presence: true

  private

  def list_done?
    list.title == 'Done'
    puts
  end

  def update_completed_at
    self.completed_at = Time.now
    save!
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board

  validates :title, presence: true
  has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
end

app/controllers/api/item_positions_controller.rb
module Api
  class ItemPositionsController < ApplicationController
    protect_from_forgery with: :null_session
    def update
      items = items_params[:items].map do |item_data|
        item = Item.find(item_data[:id])
        item.position = item_data[:position]
        item.list_id = item_data[:list_id]
        item
      end
      Item.import items, on_duplicate_key_update: { conflict_target: [:id], columns: [:position, :list_id] }
      render json: ItemSerializer.new(items).serializable_hash.to_json
    end

    private

    def items_params
      params.permit(items: [:id, :position, :list_id])
    end
  end
end

app/controllers/api/items_controller.rb
module Api
    class ItemsController < ApplicationController
      protect_from_forgery with: :null_session, only: :destroy
  
      def show
        item = Item.find(params[:id])
  
        render json: ItemSerializer.new(item).serializable_hash.to_json
      end
    end
  end

app/controllers/api/list_positions_controller.rb
module Api
    class ListPositionsController < ApplicationController
        protect_from_forgery with: :null_session

        def index
            @lists = board.lists.order(position: :asc)

            render json: ListSerializer.new(@lists).serializable_hash.to_json
        end


        def update
            lists = board.lists.to_a
            delete_index = lists.index { |list| list.id == params[:id].to_i }
            list = lists.delete_at(delete_index)
            lists.insert(params[:position].to_i, list)
            lists.each_with_index do |list, index|
                list.position = index
            end

            List.import lists, on_duplicate_key_update: { conflict_target: [:id], columns: [:position]}

            render json: ListSerializer.new(lists).serializable_hash.to_json

        end

        private

        def board
            @board ||= Board.find(params[:board_id])
        end
    end
end

app/controllers/api/lists_controller.rb
module Api
    class ListsController < ApplicationController
        protect_from_forgery with: :null_session
        def index
            @lists = board.lists.order(position: :asc)

            render json: ListSerializer.new(@lists).serializable_hash.to_json
        end

        private

        def board
            @board ||= Board.find(params[:board_id])
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit::Authorization
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!

  def new
    @board = Board.new
  end

  def edit
    authorize board
  end

  def show
    authorize board
  end

  def create
    @board = Board.new(board_params.merge(user: current_user))

    if @board.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    authorize board

    if @board.update(board_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    authorize board
    @board.destroy
    redirect_to root_path
  end

  private

  def board_params
    params.require(:board).permit(:name)
  end

  def board
    @board ||= Board.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :authenticate_user!

  def index
    @boards = Board.order(:created_at)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        redirect_to dashboard_path if user_signed_in?
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :authenticate_user!

    protect_from_forgery with: :null_session, only: :destroy

    def new
      @item = list.items.new
    end

    def edit
      @item = list.items.find(params[:id])
    end

    def update
      @item = list.items.find(params[:id])

      if @item.update(items_params)
        redirect_to board_path(list.board)
      else
        render :edit
      end
    end

    def create
      @item = list.items.new(items_params)

      if @item.save
        redirect_to board_path(list.board)
      else
        render :new
      end
    end

    def destroy
      @item = list.items.find(params[:id])
      @item.destroy
      respond_to do |format|
        format.json do
          render json: {}, status: 200
        end
      end
    end

    private

    def list
      @list ||= List.find(params[:list_id])
    end

    def items_params
      params.require(:item).permit(:title, :description)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :authenticate_user!

    protect_from_forgery with: :null_session, only: :destroy

    def new
      @list = board.lists.new
    end

    def edit
      @list = board.lists.find(params[:id])
    end

    def update
      @list = board.lists.find(params[:id])

      if @list.update(list_params)
        redirect_to board_path(board)
      else
        render :edit
      end
    end

    def create
      @list = board.lists.new(list_params)

      if @list.save
        redirect_to board_path(board)
      else
        render :new
      end
    end

    def destroy
      @list = board.lists.find(params[:id])
      @list.destroy
      respond_to do |format|
        format.json do
          render json: {}, status: 200
        end
      end
    end

    private

    def board
      @board ||= Board.find(params[:board_id])
    end

    def list_params
      params.require(:list).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.erb
<%= form_with model: @board, local: true, class: "space-y-8 divide-gray-200" do |f| %>
    <div class="relative px-4 py-10 bg-white mx-8 md:mx-0 shadow rounded-3xl sm:p-10">
      <div class="max-w-md mx-auto">
        <div class="flex items-center space-x-5">
          <div class="h-14 w-14 bg-yellow-200 rounded-full flex flex-shrink-0 justify-center items-center text-yellow-500 text-2xl font-mono">i</div>
          <div class="block pl-2 font-semibold text-xl self-start text-gray-700">
            <% if board.new_record? %>
                <h2 class="leading-relaxed">Criar um cartão</h2>
                <p class="text-sm text-gray-500 font-normal leading-relaxed">Esse formulário cria um cartão, por favor preencha os campos.</p>
            <% else %>
             <h2 class="leading-relaxed">Editar um cartão</h2>
             <p class="text-sm text-gray-500 font-normal leading-relaxed">Esse formulário edita um cartão, por favor preencha os campos.</p>
            <% end %>
          </div>
        </div>
        <div class="divide-y divide-gray-200">
          <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
            <div class="flex flex-col">
              <%= f.label :name, class: "leading-loos"%>
              <%= f.text_field :name, class: "px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600"%>
            </div>
           
          <div class="pt-4 flex items-center space-x-4">
            <%= link_to "Cancel", root_path, class: "flex justify-center items-center w-full text-gray-900 px-4 py-3 rounded-md focus:outline-none"%>
            <%= f.submit "Criar", class: "bg-blue-500 flex justify-center items-center w-full text-white px-4 py-3 rounded-md focus:outline-none"%>
          </div>
        </div>
      </div>
    </div>
    <% end %>

app/views/boards/edit.html.erb
<div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
  <div class="relative py-3 sm:max-w-xl sm:mx-auto">
    <%= render "form", board: @board %>
  </div>
</div>

app/views/boards/new.html.erb
<%= form_with model: @board, local: true, class: "space-y-8 divide-gray-200" do |f| %>
    <div class="min-h-screen p-6 bg-gray-100 flex items-center justify-center">
        <div class="container max-w-screen-lg mx-auto">
            <div>
                <h2 class="font-semibold text-xl text-gray-600">Novo cartão</h2>
                <p class="text-gray-500 mb-6">Esse formulário cria um novo cartão</p>
                    <div class="bg-white rounded shadow-lg p-4 px-4 md:p-8 mb-6">
                        <div class="grid gap-4 gap-y-2 text-sm grid-cols-1 lg:grid-cols-3">
                            <div class="text-gray-600">
                                <p class="font-medium text-lg">Preencha os dados</p>
                            </div>
                            <div class="lg:col-span-2">
                                <div class="grid gap-4 gap-y-2 text-sm grid-cols-1 md:grid-cols-5">
                                    <div class="md:col-span-5">
                                        <%= f.label :name, class: "d:col-span-5"%>
                                        <%= f.text_field :name, class: "h-10 border mt-1 rounded px-4 w-full bg-gray-50"%>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
            <div class="pt-5">
                <div class="flex justify-end">
                    <%= link_to "Cancel", root_path, class: "text-black bg-red-700 hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900"%>
                    <%= f.submit "Criar", class: "px-3 py-2 text-xs font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"%>
                </div>
            </div>
            </div>
            </div>
        </div>
    </div>
<% end %>

app/views/boards/show.html.erb
<div class="mx-auto max-w-7xl px-24 py-12">
    <div data-controller="board" data-board-lists-url="<%= board_lists_path(@board)%>" data-list-positions-api-url="<%= api_board_list_positions_path(@board)%>" data-api-url="<%= api_board_lists_path(@board) %>" data-item-positions-api-url="<%= api_item_positions_path%>" class="mx-auto max-w-4xl" id="board" style="overflow-x: scroll;">
    </div>

    <h2> Dashboard </h2>

    <% list_titles = List.pluck(:id, :title).to_h %>
    <% list_item_counts = Item.group(:list_id).count %>
    <% list_counts = list_item_counts.transform_keys { |list_id| list_titles[list_id] } %>

    <%= column_chart list_counts  %>

    <% completed_task = Item.where.not(updated_at: nil).group("DATE(updated_at)").count %>

    <% data = completed_task.map { |date, count| { date: date, count: count } } %>


    <%= line_chart completed_task %>

</div>
<%= render "shared/modal" %>

app/views/dashboard/index.html.erb
<div class="mx-auto max-w-lx px-4 sm:px-6 lg:px-8 py-12">
    <div class="mx-auto max-w-3xl">
        <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
            <% @boards.each do |board|%>
                <li class="col-span-1 divide-y divide-gray-200 rounded-lg bg-white shadow">
                    <div class="flex w-full items-center justify-between space-x-6 p-6">
                        <div class="flex-1 truncate">
                            <div class="flex items-centers space-x-3">
                                <h3 class="truncate text-sm font-medium text-gray-900"><%= link_to board.name, board_path(board), class: "link" %>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="-mt-px flex divide-x divide-gray-200">
                            <div class="flex w-0 flex-1">
                                <%= link_to edit_board_path(board), class: "relative -mr-px inline-flex w-0 flex-1 items-center justify-center rounded-bl-lg border border-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500" do%>
                                    <span class="ml-3">Editar</span>
                                <% end %>
                            </div>
                            <div class="-ml-px flex w-0 flex-1">
                                <%= link_to board_path(board), data: { "turbo-method": :delete }, class: "relative inline-flex w-0 flex-1 items-center justify-center rounded-br-lg border border-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500" do %>
                                    <span class="ml-3 text-red-700">Deletar</span>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </li>
            <%  end %>
        </ul>
    </div>
</div>

app/views/home/index.html.erb
<p>hello world</p>

app/views/items/_form.html.erb
<div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
  <div class="relative py-3 sm:max-w-xl sm:mx-auto">
    <%= form_with model: [list, item], local: true, class: "space-y-8 divide-gray-200" do |f| %>
    <div class="relative px-4 py-10 bg-white mx-8 md:mx-0 shadow rounded-3xl sm:p-10">
      <div class="max-w-md mx-auto">
        <div class="flex items-center space-x-5">
          <div class="h-14 w-14 bg-yellow-200 rounded-full flex flex-shrink-0 justify-center items-center text-yellow-500 text-2xl font-mono">i</div>
          <div class="block pl-2 font-semibold text-xl self-start text-gray-700">
            <% if @item.new_record? %>
                <h2 class="leading-relaxed">Criar um item</h2>
                <p class="text-sm text-gray-500 font-normal leading-relaxed">Esse formulário cria um item, por favor preencha os campos.</p>
            <% else %>
             <h2 class="leading-relaxed">Editar um item</h2>
             <p class="text-sm text-gray-500 font-normal leading-relaxed">Esse formulário edita um item, por favor preencha os campos.</p>
            <% end %>
          </div>
        </div>
        <div class="divide-y divide-gray-200">
          <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
            <div class="flex flex-col">
              <%= f.label :title, class: "leading-loos"%>
              <%= f.text_field :title, class: "px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600"%>
            </div>

             <div class="flex flex-col">
              <%= f.label :description, class: "leading-loos"%>
              <%= f.text_area :description, class: "px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600"%>
            </div>
           
          <div class="pt-4 flex items-center space-x-4">
            <%= link_to "Cancelar", root_path, class: "flex justify-center items-center w-full text-gray-900 px-4 py-3 rounded-md focus:outline-none"%>
            <%= f.submit "Finalizar", class: "bg-blue-500 flex justify-center items-center w-full text-white px-4 py-3 rounded-md focus:outline-none"%>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/items/edit.html.erb
<%= render "form", list: @list, item: @item %>

app/views/items/new.html.erb
<div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
  <div class="relative py-3 sm:max-w-xl sm:mx-auto">
    <%= form_with model: [@list, @item], local: true, class: "space-y-8 divide-gray-200" do |f| %>
    <div class="relative px-4 py-10 bg-white mx-8 md:mx-0 shadow rounded-3xl sm:p-10">
      <div class="max-w-md mx-auto">
        <div class="flex items-center space-x-5">
          <div class="h-14 w-14 bg-yellow-200 rounded-full flex flex-shrink-0 justify-center items-center text-yellow-500 text-2xl font-mono">i</div>
          <div class="block pl-2 font-semibold text-xl self-start text-gray-700">
            <% if @item.new_record? %>
                <h2 class="leading-relaxed">Criar um item</h2>
                <p class="text-sm text-gray-500 font-normal leading-relaxed">Esse formulário cria um item, por favor preencha os campos.</p>
            <% else %>
             <h2 class="leading-relaxed">Editar um item</h2>
             <p class="text-sm text-gray-500 font-normal leading-relaxed">Esse formulário edita um item, por favor preencha os campos.</p>
            <% end %>
          </div>
        </div>
        <div class="divide-y divide-gray-200">
          <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
            <div class="flex flex-col">
              <%= f.label :title, class: "leading-loos"%>
              <%= f.text_field :title, class: "px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600"%>
            </div>
             <div class="flex flex-col">
              <%= f.label :description, class: "leading-loos"%>
              <%= f.text_field :description, class: "px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600"%>
            </div>
           
          <div class="pt-4 flex items-center space-x-4">
            <%= link_to "Cancel", root_path, class: "flex justify-center items-center w-full text-gray-900 px-4 py-3 rounded-md focus:outline-none"%>
            <%= f.submit "Criar", class: "bg-blue-500 flex justify-center items-center w-full text-white px-4 py-3 rounded-md focus:outline-none"%>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <%= link_to root_path do%>
        <%= image_tag "https://flowbite.com/docs/images/logo.svg", class: "h-8 mr-3"%>
    <% end %>
    <% if user_signed_in?%>
  <div class="flex items-center md:order-2">
        <% if controller_name == "boards" and action_name == "show" %>
        <%= link_to "New list", new_board_list_path(@board), class: "px-3 py-2 text-sm font-medium text-center inline-flex items-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"%>
        <% else%>
        <%= link_to "New board", new_board_path, class: "px-3 py-2 text-sm font-medium text-center inline-flex items-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"%>
        <% end%>

  </div>
  <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
    <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
      <li>
         <%= link_to "Tasks", root_path, class: "block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent #{"md:text-blue-700" if controller_name == 'dashboard'} md:p-0 md:dark:text-blue-500"%>
      </li>
      <li>
        <a href="#" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Dashboard</a>
      </li>
      <li>
         <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete}, class: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
      </li>
    </ul>
  </div>

  <%else%>

   <div class="ml-4 flex flex-shrink-0 items-center ">
                <%= link_to "Register", new_user_registration_path, class: "link" %>
                <%= link_to "Login", new_user_session_path, class: "ml-3 link" %>
            </div>

    <% end %>
      
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KanbanApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-200">
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
  <div class="relative py-3 sm:max-w-xl sm:mx-auto">
    <%= form_with model: [board, list], local: true, class: "space-y-8 divide-gray-200" do |f| %>
    <div class="relative px-4 py-10 bg-white mx-8 md:mx-0 shadow rounded-3xl sm:p-10">
      <div class="max-w-md mx-auto">
        <div class="flex items-center space-x-5">
          <div class="h-14 w-14 bg-yellow-200 rounded-full flex flex-shrink-0 justify-center items-center text-yellow-500 text-2xl font-mono">i</div>
          <div class="block pl-2 font-semibold text-xl self-start text-gray-700">
            <% if @list.new_record? %>
                <h2 class="leading-relaxed">Criar uma lista</h2>
                <p class="text-sm text-gray-500 font-normal leading-relaxed">Esse formulário cria uma lista, por favor preencha os campos.</p>
            <% else %>
             <h2 class="leading-relaxed">Editar uma lista</h2>
             <p class="text-sm text-gray-500 font-normal leading-relaxed">Esse formulário edita uma lista, por favor preencha os campos.</p>
            <% end %>
          </div>
        </div>
        <div class="divide-y divide-gray-200">
          <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
            <div class="flex flex-col">
              <%= f.label :title, class: "leading-loos"%>
              <%= f.text_field :title, class: "px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600"%>
            </div>
           
          <div class="pt-4 flex items-center space-x-4">
            <%= link_to "Cancel", root_path, class: "flex justify-center items-center w-full text-gray-900 px-4 py-3 rounded-md focus:outline-none"%>
            <%= f.submit "Criar", class: "bg-blue-500 flex justify-center items-center w-full text-white px-4 py-3 rounded-md focus:outline-none"%>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/lists/edit.html.erb
<%= render "form", board: @board, list: @list %>

app/views/lists/new.html.erb
<div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
  <div class="relative py-3 sm:max-w-xl sm:mx-auto">
    <%= form_with model: [@board, @list], local: true, class: "space-y-8 divide-gray-200" do |f| %>
    <div class="relative px-4 py-10 bg-white mx-8 md:mx-0 shadow rounded-3xl sm:p-10">
      <div class="max-w-md mx-auto">
        <div class="flex items-center space-x-5">
          <div class="h-14 w-14 bg-yellow-200 rounded-full flex flex-shrink-0 justify-center items-center text-yellow-500 text-2xl font-mono">i</div>
          <div class="block pl-2 font-semibold text-xl self-start text-gray-700">
            <% if @list.new_record? %>
                <h2 class="leading-relaxed">Criar uma lista</h2>
                <p class="text-sm text-gray-500 font-normal leading-relaxed">Esse formulário cria uma lista, por favor preencha os campos.</p>
            <% else %>
             <h2 class="leading-relaxed">Editar uma lista</h2>
             <p class="text-sm text-gray-500 font-normal leading-relaxed">Esse formulário edita uma lista, por favor preencha os campos.</p>
            <% end %>
          </div>
        </div>
        <div class="divide-y divide-gray-200">
          <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
            <div class="flex flex-col">
              <%= f.label :title, class: "leading-loos"%>
              <%= f.text_field :title, class: "px-4 py-2 border focus:ring-gray-500 focus:border-gray-900 w-full sm:text-sm border-gray-300 rounded-md focus:outline-none text-gray-600"%>
            </div>
           
          <div class="pt-4 flex items-center space-x-4">
            <%= link_to "Cancel", root_path, class: "flex justify-center items-center w-full text-gray-900 px-4 py-3 rounded-md focus:outline-none"%>
            <%= f.submit "Criar", class: "bg-blue-500 flex justify-center items-center w-full text-white px-4 py-3 rounded-md focus:outline-none"%>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_modal.html.erb
<div
  data-controller="modal"
  id="modal-wrapper"
  class="hidden relative z-10"
  aria-labelledby="modal-title"
  role="dialog"
  aria-modal="true"
>  
  <div class="hidden" id="show-modal-div" data-action="click->modal#showModal"></div>
  <div
    id="modal-backdrop"
    class="hidden fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
    data-transition-enter="ease-out duration-300"
    data-transition-enter-start="opacity-0"
    data-transition-enter-end="opacity-100"
    data-transition-leave="ease-in duration-200"
    data-transition-leave-start="opacity-100"
    data-transition-end="opacity-0" 
  ></div>
  <div class="fixed z-10 inset-0 overflow-y-auto">  
    <div class="flex items-end sm:items-center justify-center min-h-full p-4 text-center sm:p-0">
      <div
        id="modal-panel"
        class="hidden relative bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all w-2/4 text-sm"
        data-transition-enter="ease-out duration-300"
        data-transition-enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        data-transition-enter-end="opacity-100 translate-y-0 sm:scale-100"
        data-transition-leave="ease-in duration-200"
        data-transition-leave-start="opacity-100 translate-y-0 sm:scale-100"
        data-transition-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        >

        <div class="flex mb-5">
          <div class="flex-none cursor-pointer" data-modal-target="closeButton">
            <svg class="w-4 h-4 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 8 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 1 1.3 6.326a.91.91 0 0 0 0 1.348L7 13"/>
            </svg>
          </div>
        </div>
        <div>
          <p class="font-bold tracking-wide">Title:</p>
          <p id="item-title" class="tracking-wide mb-5"></p>

          <p class="font-bold tracking-wide">Description:</p>
          <p id="item-description" class="tracling-wide mb-5"></p>

          <div class="flex">
            <div><%= link_to "Editar", "", class: "link" ,id: "item-edit-link" %></div>
            <div class="ml-4"><%= link_to "Deletar", "", class: "link", style: "color: red", color: "text-red-700", id: "item-delete-link" %></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>  